services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indegodb
    ports:
      - "5432:5432"
    networks:
      - go-bike-network
  go-bike:
    image: go-bike:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      DATBASE_URL: postgres://user:password@postgres/indegodb?sslmode=disable
    networks:
      - go-bike-network
networks:
  go-bike-network:
    driver: bridge