CREATE TABLE IF NOT EXISTS stations (
    id SERIAL PRIMARY KEY,
    at TIMESTAMP NOT NULL,
    name VARCHAR(255) NOT NULL,
    kiosk_id INTEGER,
    is_event_based BOOL NOT NULL,
    is_virtual BOOL NOT NULL,
    total_docks INTEGER,
	trikes_available INTEGER,
	docks_available INTEGER,
	bikes_available INTEGER,
	classic_bikes_available INTEGER,
	smart_bikes_available INTEGER,
	electric_bikes_available INTEGER,
	reward_bikes_available INTEGER,
	reward_docks_available INTEGER,
	kiosk_type INTEGER,
    latitude NUMERIC(10, 8) NOT NULL,
	longitude NUMERIC(11, 8) NOT NULL,
	kiosk_status VARCHAR(50) NOT NULL,
	kiosk_public_status VARCHAR(50) NOT NULL,
	kiosk_connection_status VARCHAR(50) NOT NULL,
	address_street VARCHAR(100) NOT NULL,
	address_city VARCHAR(100) NOT NULL,
	address_state VARCHAR(100) NOT NULL,
	address_zipcode VARCHAR(50) NOT NULL,
	close_time VARCHAR(50) NOT NULL,
	event_end VARCHAR(50) NOT NULL,
	event_start VARCHAR(50) NOT NULL,
	notes VARCHAR(255) NOT NULL,
	open_time VARCHAR(50) NOT NULL,
	public_text VARCHAR(255) NOT NULL,
	timezone VARCHAR(50) NOT NULL,
    coordinates NUMERIC[]
)