Authorization:
  Token: 123456789

Database:
  Host: "postgres"
  Port: "5432"
  User: "adriel"
  Password: "artiza"
  Name: "indegodb"

ThirdpartAPI:
  APIKey: "weather_api_key_here"
  CurrentWeather: "https://api.openweathermap.org/data/2.5/weather"
  City: "Philadelphia"
  BicycleTrancit: "https://bts-status.bicycletransit.workers.dev/phl"


  